export enum CartApiErrorCode {
  INVALID_CART_DATA = "INVALID_CART_DATA",
  CART_NOT_FOUND = "CART_NOT_FOUND",
  CART_ACCESS_DENIED = "CART_ACCESS_DENIED",
  INVALID_GET_CART_REQUEST_PAYLOAD = "INVALID_GET_CART_REQUEST_PAYLOAD",
  INVALID_UPDATE_CART_REQUEST_PAYLOAD = "INVALID_UPDATE_CART_REQUEST_PAYLOAD",
}
